// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmLZMJmj4M392ofeshjJzzKkIHU83QtX8',
    appId: '1:757205054497:web:2c35e42aeccc5b2c565f60',
    messagingSenderId: '757205054497',
    projectId: 'maonaroda-6cd9c',
    authDomain: 'maonaroda-6cd9c.firebaseapp.com',
    databaseURL: 'https://maonaroda-6cd9c-default-rtdb.firebaseio.com',
    storageBucket: 'maonaroda-6cd9c.appspot.com',
    measurementId: 'G-P7XT4CQ6DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYGxeePEw6GRh7wVtGTn_xdmlAN-QM4F8',
    appId: '1:757205054497:android:fe124643c75b12e0565f60',
    messagingSenderId: '757205054497',
    projectId: 'maonaroda-6cd9c',
    databaseURL: 'https://maonaroda-6cd9c-default-rtdb.firebaseio.com',
    storageBucket: 'maonaroda-6cd9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbm2gCaX3T6zPzVkd9_jCUhPPQarCahUk',
    appId: '1:757205054497:ios:00be5998ab4b463d565f60',
    messagingSenderId: '757205054497',
    projectId: 'maonaroda-6cd9c',
    databaseURL: 'https://maonaroda-6cd9c-default-rtdb.firebaseio.com',
    storageBucket: 'maonaroda-6cd9c.appspot.com',
    iosBundleId: 'com.example.appMaoNaRoda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbm2gCaX3T6zPzVkd9_jCUhPPQarCahUk',
    appId: '1:757205054497:ios:00be5998ab4b463d565f60',
    messagingSenderId: '757205054497',
    projectId: 'maonaroda-6cd9c',
    databaseURL: 'https://maonaroda-6cd9c-default-rtdb.firebaseio.com',
    storageBucket: 'maonaroda-6cd9c.appspot.com',
    iosBundleId: 'com.example.appMaoNaRoda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmLZMJmj4M392ofeshjJzzKkIHU83QtX8',
    appId: '1:757205054497:web:e4e3b3ecdd907614565f60',
    messagingSenderId: '757205054497',
    projectId: 'maonaroda-6cd9c',
    authDomain: 'maonaroda-6cd9c.firebaseapp.com',
    databaseURL: 'https://maonaroda-6cd9c-default-rtdb.firebaseio.com',
    storageBucket: 'maonaroda-6cd9c.appspot.com',
    measurementId: 'G-G7FB6RB44T',
  );
}
